Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server-2025-standard"
  config.vm.box_version = "2402.0.2505"
  config.vm.define "pantheon-enfers"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "pantheon-enfers"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/playbooks/windows_initial_setup.yml"
    ansible.inventory_path = "../../ansible/inventory/vagrant_inventory.yml"
    ansible.extra_vars = {
      ansible_winrm_server_cert_validation: "ignore",
      target_host: "pantheon-enfers",
      server_type: "enfers",
      data_path: "../../ansible/vars"
    }
  end
end 
 
