Vagrant.configure("2") do |config|
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
  end

  # Contrôleur de domaine Windows
  config.vm.define "dc-win" do |dcwin|
    dcwin.vm.box = "StefanScherer/windows_2022"
    dcwin.vm.hostname = "dc-win.vulnad.local"
    dcwin.vm.network "private_network", ip: "192.168.56.10"
    dcwin.vm.communicator = "winrm"
    dcwin.vm.provider "vmware_desktop" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  # Contrôleur de domaine Linux secondaire
  config.vm.define "dc-linux" do |dclin|
    dclin.vm.box = "generic/debian12"
    dclin.vm.hostname = "dc-linux.vulnad.local"
    dclin.vm.network "private_network", ip: "192.168.56.11"
    dclin.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  # Serveur ADCS
  config.vm.define "adcs" do |adcs|
    adcs.vm.box = "StefanScherer/windows_2022"
    adcs.vm.hostname = "adcs.vulnad.local"
    adcs.vm.network "private_network", ip: "192.168.56.12"
    adcs.vm.communicator = "winrm"
    adcs.vm.provider "vmware_desktop" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  # Serveur Wazuh
  config.vm.define "wazuh" do |wazuh|
    wazuh.vm.box = "generic/debian12"
    wazuh.vm.hostname = "wazuh.vulnad.local"
    wazuh.vm.network "private_network", ip: "192.168.56.13"
    wazuh.vm.provider "vmware_desktop" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  # Machine attaquante Kali
  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali.vulnad.local"
    kali.vm.network "private_network", ip: "192.168.56.14"
    kali.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  # Client Windows 1
  config.vm.define "win-client1" do |client1|
    client1.vm.box = "gusztavvargadr/windows-10"
    client1.vm.hostname = "win-client1.vulnad.local"
    client1.vm.network "private_network", ip: "192.168.56.15"
    client1.vm.communicator = "winrm"
    client1.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  # Client Windows 2
  config.vm.define "win-client2" do |client2|
    client2.vm.box = "gusztavvargadr/windows-10"
    client2.vm.hostname = "win-client2.vulnad.local"
    client2.vm.network "private_network", ip: "192.168.56.16"
    client2.vm.communicator = "winrm"
    client2.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end
