# Début de la configuration Vagrant avec la version 2 de l'API
Vagrant.configure("2") do |config|
  # Définition de la box Vagrant à utiliser pour toutes les machines virtuelles
  config.vm.box = "generic/debian12"

  # Définition de la machine virtuelle "jenkins"
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.10"
  end

  # Définition de la machine virtuelle "dev"
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.11"
  end

  # Définition de la machine virtuelle "test"
  config.vm.define "test" do |test|
    test.vm.hostname = "test"
    test.vm.network "private_network", ip: "192.168.56.12"
  end

  # Ici, le port 80 de la machine virtuelle est accessible via le port 8080 de l'hôte
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  # Définition de la plage de ports utilisables pour les transferts de ports
  config.vm.usable_port_range = (8000..9000)
end

