Vagrant.configure("2") do |config|
  config.vm.define "linux" do |linux|
    linux.vm.box = "ubuntu/bionic64"
    linux.vm.hostname = "linux"

    # Réseau privé (accès depuis l'hôte uniquement)
    linux.vm.network "private_network", ip: "192.168.56.10"

    # Synchro des fichiers Ansible
    linux.vm.synced_folder "../../ansible", "/home/vagrant/ansible"

    # Préinstall Python3 + configuration des locales pour Ansible
    linux.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y python3 language-pack-fr
      sudo locale-gen fr_FR.UTF-8
      sudo update-locale LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8
      echo "export LANG=fr_FR.UTF-8" | sudo tee -a /etc/profile
      echo "export LC_ALL=fr_FR.UTF-8" | sudo tee -a /etc/profile
    SHELL

    # Provision Ansible local dans la VM
    linux.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/home/vagrant/ansible/playbooks/main.yml"
      ansible.compatibility_mode = "2.0"
      ansible.extra_vars = {
        ansible_python_interpreter: "/usr/bin/python3"
      }
    end
  end
end

 
