Vagrant.configure("2") do |config|
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_version = "2021.05.15"
  config.vm.define "pantheon-ca01"
  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "pantheon-ca01"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/playbooks/initial_setup.yml"
    ansible.inventory_path = "../../ansible/inventory/vagrant_inventory.yml"
    ansible.extra_vars = {
      ansible_winrm_server_cert_validation: "ignore",
      target_host: "pantheon-ca01",
      server_type: "ca01"
    }
  end
end 