Vagrant.configure("2") do |config|

    config.vm.network "private_network", type: "dhcp"
    config.vm.define "ad" do |ad|

      ad.vm.box = "gusztavvargadr/windows-10"
      ad.vm.hostname = "ad" 
      ad.vm.communicator = "winrm"

      ad.vm.provider "virtualbox" do |vb|
        vb.name = "ad"
        vb.memory = "4096"
        vb.cpus = 2
      end
      config.vm.provision "shell", path: "scripts/setup-postreboot-task.ps1"
      config.vm.provision "shell", path: "scripts/install-ad.ps1"
    end
end

    # config.vm.define "ubuntu" do |ubuntu|
    #   ubuntu.vm.box = "ubuntu/trusty64"
    #   ubuntu.vm.hostname = "ubuntu"
  
  
  
    #   ubuntu.vm.provision :ansible_local do |ansible|
    #     ansible.playbook = 'ansible/wordpress-lamp_ubuntu1804/playbook.yml'
    #   end 

    #   ubuntu.vm.provider "virtualbox" do |vb|
    #     vb.name = "ubuntu"
    #     vb.memory = "4096"
    #     vb.cpus = 2
    #   end
  
    # end
  