Vagrant.configure("2") do |config|
  # Réseau
  config.vm.network "private_network", type: "dhcp"

  # Machine 1: Contrôleur de domaine (Windows Server 2019)
  config.vm.define "dc" do |dc|
    dc.vm.box = "StefanScherer/windows_2019"
    dc.vm.hostname = "DC"
    dc.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    dc.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/dc_setup.yml"
    end
  end

  # Machine 2: Client Windows (Windows 10)
  config.vm.define "win_client" do |win|
    win.vm.box = "StefanScherer/windows_10"
    win.vm.hostname = "Win10"
    win.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Machine 3: Linux Vulnérable (Kali)
  config.vm.define "kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "Kali"
    kali.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    kali.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/kali_setup.yml"
    end
  end
end
