Vagrant.configure("2") do |config|
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
  end
  config.vm.box = "generic/debian12"

  # Configuration du provisionnement pour la machine virtuelle
  config.vm.provision "shell", inline: <<-SHELL
    # Mise à jour des paquets
    sudo apt-get update

    # Installation des outils nécessaires
    sudo apt-get install -y software-properties-common

    # Ajout du dépôt Ansible et mise à jour
    sudo add-repository --yes --update ppa:ansible/ansible

    # Installation d'Ansible
    sudo apt-get install -y ansible
  SHELL
end
